### ISSUE TITLE
Date displaying twice in record

### ISSUE THREAD

**Issue by catlu** [sciencehistory/chf-sufia#1049] opened 2018-04-25 16:05 UTC
It's only entered once in the edit form. Seen here: https://digital.sciencehistory.org/works/9019s320q and here: https://digital.sciencehistory.org/works/ft848r50m.

**Comment by archivistsarah** [comment] 2018-04-26 15:18
I think this is happening only when adding a date to an existing work that didn't previously have the date field filled in, and not to dates added as part of ingest or editing an existing date entry. 

Appearing twice for this one (in which I added a date where there wasn't one before):
https://digital.sciencehistory.org/works/7h149p955

Appearing only once for this work (in which I changed "undated" to "1970s"):
https://digital.sciencehistory.org/works/1831cj92z

Works newly ingested & described this week are fine (ingested 4/26/2018): https://digital.sciencehistory.org/works/4b29b690d

**Comment by jrochkind** [comment] 2018-04-26 19:09
If I enter 1900, decade, I get "decade starting 1900s" which probably isn't quite English. 

Should probably be "decade starting 1900", or "1900s (decade)". The parenthetical qualifier seems a bit more readable to me for both century and decade, but no strong opinions. 

Also getting the duplicated dates when I edit a field too. Very mysterious! Wonder if this is a bug in _my_ Solr indexing stuff, hmm.

**Comment by jrochkind** [comment] 2018-04-26 19:09
We will want to get dates fixed before we send to PA Digital for DPLA, cause I'm using this stuff in the OAI-PMH field now!

**Comment by jrochkind** [comment] 2018-05-03 14:34
Okay, I guess ignore my issue if you can't reproduce!

**Comment by eddierubeiz** [comment] 2018-05-03 19:50
Hey @catlu and @archivistsarah  -- I think this is fixed in production. Please let me know if the bug comes back. I have reason to believe that it won't.

**Comment by eddierubeiz** [comment] 2018-05-03 19:51
Oh and thanks for testing last week, obviously!

**Closed** 2018-05-03 19:54 UTC
Labels: bug
