### ISSUE TITLE
Update user accounts with new email addresses

### ISSUE THREAD

**Issue by sanfordd** [sciencehistory/chf-sufia#963] opened 2018-01-23 20:57 UTC
We will need to update user accounts with the new email addresses, autoforwarding will handle things for a time but keeping the old ones around seems like a recipe for something breaking a few years from now.

~A quick database update should be all we need.~ (wishful thinking)

**Comment by jrochkind** [comment] 2018-01-24 22:17
I thought I recalled discussing this and deciding not to worry about it for now, and not to do it before rebrand launch. @MDiMeo ?

**Comment by jrochkind** [comment] 2018-02-06 16:14
Harder than anticipated, asked for advice on samvera-tech. https://groups.google.com/forum/#!topic/samvera-tech/ZeruxuBObuk

**Comment by jrochkind** [comment] 2018-02-07 16:04
It turns out there's really no supported way to do this, and the architecture makes it very difficult to figure out how to do it reliably. 

I will continue trying, but hard to be sure something hasn't fallen through the cracks, will require lots of testing of everything we can think of, and an acceptance that something might not work quite right.

**Comment by jrochkind** [comment] 2018-02-07 16:09
also going to take many hours to run the migration.

**Comment by jrochkind** [comment] 2018-02-07 17:10
Okay, I can change the `depositor` on works and filesets, which _should_ preserve access to works you personally submitted. (Still will need testing). 

It will take ~20+ hours to migrate. 

Other things would be preserving access that an individual account has been granted on the "share" tab, and preserving membership of "groups" we have created. Not totally sure if we use either feature.

**Comment by jrochkind** [comment] 2018-02-07 17:15
Also, oops, even with just "depositor" change, the old @chemheritage.org email address for the user still shows up in "Sharing" tab as "shared with". 

Have to figure out where permissions are stored to fix that, or fix any existing "shared with" people.

**Comment by jrochkind** [comment] 2018-02-12 18:57
Running migration on staging took a bit over 3 hours. Estimate maybe 4 hours for production. While migration is running, things are in a weird inconsistent state where users may see some of the works they have permissions to, but not others.

**Comment by catlu** [comment] 2018-02-20 16:29
I was able to log in with @sciencehistory.org just fine and access all works, though I think that's because of my admin access, so I can't say for sure if there isn't loss of permissions. I'm also still able to access/edit collections from the Browse Collections section, but when I go to My Collections, I don't see anything there.

**Comment by jrochkind** [comment] 2018-02-20 16:36
Ah, "My Collections" is something I hadn't checked on. I will look into it, thanks!

**Comment by archivistsarah** [comment] 2018-02-20 16:45
re: permissions I just tested sharing a work w/ edit permissions with @mhpmiller and while she can see the work if I set visibility to "the institute" she can't edit it, nor does the work show up under her "shared with me" tab
https://staging.digital.sciencehistory.org/works/1c18dg441

**Comment by jrochkind** [comment] 2018-02-20 16:46
@archivistsarah darnit!  is this something you are sure worked previously?  

You added the edit permission for @mhpmiller just today?

**Comment by archivistsarah** [comment] 2018-02-20 16:48
@jrochkind I'm not sure where we left permissions when we stopped using them, honestly. I know they were buggy & that's why we stopped, but don't remember the specifics. Don't know if this is new, sorry. 
And yes, created the work and the permissions this morning.

**Comment by jrochkind** [comment] 2018-02-20 17:16
@archivistsarah my educated guess is that was a pre-existing problem and not new; I don't think there is any reason the change in email addresses would effect the behavior of a _new_ permission you added.  

This is somewhat difficult to confirm unless we test it on production at this point. If this is functionality we're currently using or anticipate using, we should probably test it on production to make sure "it was broken before", and the email change does not make it worse (a "regression" in technical speak). 

If we don't use it and don't foresee using it anyway, we could just proceed.

**Comment by archivistsarah** [comment] 2018-02-20 17:24
I hate saying something will never be used, but yeah, I don't anticipate anyone using permissions this way in the near future. @catlu ?

**Comment by jrochkind** [comment] 2018-02-20 21:28
@catlu @archivistsarah I think Collections permissions should now be properly updated too, thanks for the catch. Can you confirm, and then I think we're good to deploy?

**Comment by archivistsarah** [comment] 2018-02-20 21:30
I still don't see my collections listed under that tab on staging

**Comment by jrochkind** [comment] 2018-02-20 21:30
Gah, okay thanks @archivistsarah. Can you give me the name or ID of a collection you expect there?

**Comment by archivistsarah** [comment] 2018-02-20 21:31
https://staging.digital.sciencehistory.org/collections/wh246s128

**Comment by jrochkind** [comment] 2018-02-20 22:27
okay, collections are a mess. 

A) Right now, no collections in staging have any permissions assigned to them. It's possible my migration script erased them due to a bug. 

But worse, 

B) Sufia makes it awful to edit collections, including changing permissions on them. The more items in the collection, the longer and more dangeorus it is to edit, taking many minutes. Not sure what to do.

**Comment by jrochkind** [comment] 2018-03-07 17:48
Running migration script on staging took 85 hours. :( In large part, because we exhausted our EC2 CPU allotment. 

Might be worth trying doing email migration with solr indexing disabled (somehow), then doing a bulk solr index afterwords, might actually place less stress on solr and other parts of stack, which may be doing things inefficiently by default. 

Also worth considering if we really need to do this at all.

**Closed** 2018-03-19 21:55 UTC

**Comment by jrochkind** [comment] 2018-03-20 14:17
Ran in production, seems to have worked. Saga of how I got it working posted to samvera-tech list: https://groups.google.com/d/msg/samvera-tech/ZeruxuBObuk/zS-yEXIXCQAJ
