### ISSUE TITLE
implement 'recent items' section of front page

### ISSUE THREAD

**Issue by hackmastera** [sciencehistory/chf-sufia#538] opened 2017-05-18 16:50 UTC

**Comment by MDiMeo** [comment] 2017-05-18 16:56
How will the Recently Added Items section of the website work, and do we need to adjust the design to accommodate technical functionality? Currently, they have little cubes showing, but most of our images have been cropped to fit into squares at other parts of the website design. Most of the items in our digital collection are not naturally square shaped. We could probably identify some common sizes, but there are many variants. Will it crop on the fly? And if so, how awful will that look? 

For now, I am assuming this will somehow be an automated process and so I have not included it in this list of items queued up for crops: https://docs.google.com/spreadsheets/d/1D4HFGb0Yy4iFDiRrbw9LKN51Dld8YAXklLAbAp0ZRTM/edit#gid=0
However, if it makes more sense to bank a selection of cropped images that will refresh in a new order upon each page load, let me know and we can add that into our prep work.

**Comment by jrochkind** [comment] 2017-05-18 18:37
I was thinking we could maybe leave "Recently Added"  out, until we've finished other stuff, and then add it in later. I was assuming it would be automated yes.

**Comment by jrochkind** [comment] 2017-05-18 19:12
on the other hand, it's probably not hard to implement.

**Comment by MDiMeo** [comment] 2017-05-18 19:47
Yes, it can be left till later. Just creating an issue to return to these thought when we're ready to implement!

**Comment by jrochkind** [comment] 2017-05-22 15:40
anna [11:38 AM] 
@jrochkind Just that the data in it didn’t look weird. My hypothesis had been that it had added additional values into the field and only the old value was showing up. But it was as-expected: a single value (the old one) (edited)

jrochkind [11:39 AM] 
Ah, the single value was still the old one. So looked fine, but indeed had not been updated, okay, thanks!

[11:40] 
My guess is this _might_ have something to do with ‘strongparams’, I already fixed one bug related to that, so we might wanna see if we can still reproduce after we deploy ag

**Comment by HKativa** [comment] 2018-06-11 19:55
6/11/2018: I moved this ticket from backlog to post-launch and we discussed ideas for proceeding with this feature at tech check-in meeting. Informed by browsing behavior captured on Google Analytics, we'd like to build something that serves as an entry point into digital collections, creates another access point for users to explore collection. For that reason, this feature does not have to strictly highlight recent/newly added items. We discussed using recently modified rather than creation date to parse results, underscoring items with recent changes (new metadata, etc.), recognizing that most of our activity over the long-term may focus on editing existing records rather than ingesting new content. We could also conceive of this as a "what's trending" feature.

**Comment by eddierubeiz** [comment] 2018-06-11 20:12
Sounds good. Based on the comments above and our quick discussion today,
I'm assuming:
- by "front page" we mean https://digital.sciencehistory.org/  
-  the images will be cropped automatically at view time to a fixed square size
- we can have a quick meeting about the design for this feature (where does it go on the front page, how many items on each line at various screen widths, and so on.)
- A recipe to start out with in selecting which items to display: sort by modified date; pick the most recent X items; pick Y of these at random; rotate this random selection every Z minutes. (Or every time the user reloads the browser, but I prefer the former).

**Comment by jrochkind** [comment] 2018-06-11 20:21
> the images will be cropped automatically at view time to a fixed square size

I don't know if they need to be square, I was thinking we'd use the existing thumb derivatives. If they do need to be square, we could either deliver the non-square thumb and crop in CSS, or make a square derivative. I guess I'd lean toward the former, now that I think about it, agreed. 

>  rotate this random selection every Z minutes.

If it's every Z minutes, rather than every page load... we gotta cache it somewhere. :)  Which might require setting up our Rails.cache, so we can use it, since it's the right thing to use here. 

http://guides.rubyonrails.org/caching_with_rails.html#low-level-caching

http://guides.rubyonrails.org/caching_with_rails.html#cache-stores

I think it's by default the File store, which is not really appropriate. Could be memory store, or redis store. Redis store is generally what 'everyone does', we have to look into our current redis's settings and make sure it's appropriate for use as Rails.cache.

**Comment by jrochkind** [comment] 2018-06-11 20:23
I think I am imagining recent items as _just_ thumbs, no need for titles at all. Click on it if you want to find out what it is, enticed by the thumb. :) No particular imagining as to whether they are square or not. Probably another 'row' on the home page, which might require adjusting colors on other rows to fit it in graphically distinct somewhere. 

@HKativa @RonBrashear Do you have any idea if we still have the original mock-ups from the contractor anywhere, or if it's worth asking Zack if he does? Or should we just not worry about whatever the mock-up of this was months ago?

**Comment by RonBrashear** [comment] 2018-06-11 20:29
I don't have any of the mock-ups from Michelle. I'll leave it to @HKativa as to whether it's worth worrying about.

**Comment by eddierubeiz** [comment] 2018-06-11 21:07
Love the idea of no metadata, just tantalizing images.

**Comment by HKativa** [comment] 2018-06-12 14:36
@jrochkind @RonBrashear I don't think it's worth digging around for the original mock-ups, as I'm more inclined to develop this feature to fit our needs now rather than getting bogged down with what was envisioned previously. I like what @jrochkind suggests re adding another row on the homepage and having just thumbs, no metadata is enticing. My only concern is whether every image that shows up will be compelling enough to stand on its own, though that's probably not something we can control with a random pull in any case. Or maybe it would be possible the qualify 'last modified' with certain genre terms that we're more inclined to feature? I'm also wondering if we should be concerned with how a pure 'last modified' sort will skew results in favor genres that have regular activity (photos, museum objects) and effectively exclude genres like rare books, which can seen little to no activity for long periods of time.

**Comment by jrochkind** [comment] 2018-06-12 14:47
I guess, perhaps, we should try out the simple implementation before deciding if more complicated implementation is needed involving qualifying to not really be a sample of 'last modified' but a more complex attempt to show diversity of stuff?  

To me, "skewing" towards the things we are actually recently ingesting seems like possibly a feature not a bug of showing "recent additions", but we can see how it works out.

**Comment by jrochkind** [comment] 2018-06-12 14:48
Some user testing or user consultation may be indicated too.

**Comment by RonBrashear** [comment] 2018-06-12 14:50
I agree with @HKativa  that the "last modified" images will not necessarily be tantalizing enough to attract attention on their own--some basic description might be necessary to encourage views. But they are what they suggest to site visitors--the latest additions, not the most interesting or typical. If we want to encourage serendipitous discovery, the idea of random images popping up would be just as helpful. But if we want to spend more time on this maybe user testing/consultation would be desirable as @jrochkind notes.

**Comment by HKativa** [comment] 2018-06-12 15:58
@jrochkind @RonBrashear agree about trying out simple implementation and serendipitous discovery as a starting point. User testing is on my radar, but may be deferred until we have a new Metadata Librarian.

**Closed** 2018-06-26 15:52 UTC
