### ISSUE TITLE
Attaching child works to parent work generates software error on save

### ISSUE THREAD

**Issue by HKativa** [sciencehistory/chf-sufia#1105] opened 2018-06-18 16:44 UTC
Scenario: You are an admin. From your "My works" page, you select a work to edit. Under the "Relationships" tab, you relate several child works to this parent work using filenames in the "search for a work" feature. Upon saving the record, you are redirected to the "Software Error (500)" page. However, when you return to the "My works" page and reopen the parent work, all child works are now related and show up in the record.   

Specific example: Adding several child works to work ID c247ds983 generated Error ID: 3f0c467a-0533-4bcf-aaa8-3290db33d0e8 in Honeybadger.

**Comment by HKativa** [comment] 2018-06-18 16:50
Note: I encountered this error with several records (ID c247ds983; ID dn39x222c; ID ks65hd14w). In one instance, ID c247ds983, the files for the child works show up in the parent work, but the "part of" relationship does not display in the records for the individual child works. The "part of" relationship does display on the child work records for ID dn39x222c and ID ks65hd14w).

**Comment by eddierubeiz** [comment] 2018-06-18 17:45
Just adding [a link to the HoneyBadger error](https://app.honeybadger.io/projects/53196/faults/37830755/a456abb4-7315-11e8-8225-5c6342de622c#notice-summary:).

**Comment by HKativa** [comment] 2018-06-19 18:55
Possibly related issue - see #1112: after relating child works to parent ID 8623hz59c generated software error on save (see above), child works show up in parent record, but relationship is not present in child records. Child record IDs:
8049g5923
5x21tg194
9880vr89z
f1881m93b
gm80hw154
bk128b84c
h415pb36g

**Comment by jrochkind** [comment] 2018-06-26 21:45
In my dev copy, I am strangely having trouble getting the "search for a work"-to-add-childworks feature to work at all. nothing shows up in my autocomplete, even though I have other works. 

Anyone have any idea what's up with that?

**Comment by jrochkind** [comment] 2018-06-26 21:49
okay got it working with some new works i created in my dev copy. 

succesfully reproduced in dev.

**Comment by eddierubeiz** [comment] 2018-06-26 21:51
Just tested the above and ""search for a work"-to-add-childworks" appears to work fine for me.

**Comment by jrochkind** [comment] 2018-06-27 18:57
This is possibly a known bug in ActiveFedora, that maybe has been fixed in later versions we aren't using yet. https://github.com/samvera/hyrax/issues/2108

Still trying to figure out for sure if that's what it is, and what the fix was inside ActiveFedora. 

What's mysterious to me is how we never encountered this before. I wonder if there is a different UI element @catlu et al had been using to add child works, and this one was always broken? I don't think that's it, but it's mysterious.

**Comment by HKativa** [comment] 2018-06-27 19:41
@jrochkind yeah that's weird. My workflow should be the same as @catlu since she's the one who showed me the workflow, but I'll review my notes just in case.

**Comment by jrochkind** [comment] 2018-06-27 20:07
Okay, this is weird and confusing. This appears to be due to a known bug in ActiveFedora, that was fixed in ActiveFedora 11.5.2+. Why we didn't encounter this bug until now is a mystery -- perhaps other changes we made, around ingest, made the code use ActiveFedora slightly differently and trigger the bug. That's just a wild guess. 

Anyway, upgrading ActiveFedora to 11.5.2 (we were previously on 11.1.6) _appears_ to fix the problem. (I need to test it more). 

To upgrade ActiveFedora to 11.5.2, I had to upgrade some other things too, to be compatible with new ActiveFedora. 

Upgrading all those things to fix this bug... for some reason _breaks_ the existing feature that automatically brings in data from our OPAC.  Which doesn't make any sense, there's no reason it should do that, _BUT_ there was a comment note from @hackmastera, left Mar 2017  when she was  upgrading to Sufia 7.2, noting the same thing -- that for mysterious reasons, upgrading one of our dependencies past a certain version, broke the OPAC record service, which I think is the thing that lets you automatically look up OPAC data on the edit screen. 

And indeed our automated tests around the "OPAC record service" break when I try upgrading things. 

But I _think_ that our staff has literally been _not using_  the OPAC record service for over a year, and I think it was already broken _for other reasons_, it's not working even _before_ I try to fix this. 

So.  I think maybe we just remove the "OPAC record service" entirely from our app, as it's not been being used. 

Phew.

**Comment by eddierubeiz** [comment] 2018-06-27 20:10
At least we have tests. I know I probably said that 10 times today, but... at least we have tests.

**Comment by jrochkind** [comment] 2018-06-27 20:46
This should be fixed in staging, unless/until someone else like @eddierubeiz puts something else on staging to test it. But if you have a chance @HKativa , can you let me know if the bug seems to be resolved in the application on staging?

**Comment by HKativa** [comment] 2018-06-28 13:31
@jrochkind thanks for the updates. It's true that the "OPAC record service" isn't actively being used so I agree that we could/should remove that from the app entirely. And I'll test this out on staging today.

**Comment by HKativa** [comment] 2018-06-28 16:19
@jrochkind I tested this workflow a few times in staging and didn't encounter any problems. :)

**Comment by jrochkind** [comment] 2018-07-02 14:20
Closed by #1121

**Closed by jrochkind** 2018-07-02 14:20 UTC
Labels: bug
